### PR TITLE
fix deleting array content when passing an array as payload

### LINKED ISSUE #476: Issue with "Updates all authentication methods by replacing them with the given ones."
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/ruby-auth0#readme) and [Examples](https://github.com/auth0/ruby-auth0/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://www.rubydoc.info/gems/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/ruby-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

There an API that supposed to update all MFA factors for a given user. Here is URL to the documentation: https://auth0.com/docs/api/management/v2#!/Users/put_authentication_methods

First of all, documentation itself is invalid. It has an example with a payload that is an object "{}", however if you send an object to the API it will respond with error:

`Auth0::BadRequest ({"statusCode":400,"error":"Bad Request","message":"Payload validation error: 'Expected type array but found type object'.","errorCode":"invalid_body"})`

Okay, but now if we send an array instead it will be send to the API as empty body. Moreover payload argument will be mutated. This is due how HTTProxy mixin work (`auth0/mixins/httpproxy.rb`):

```ruby
%i(get post post_file put patch delete delete_with_body).each do |method|
  define_method(method) do |uri, body = {}, extra_headers = {}|
    body = body.delete_if { |_, v| v.nil? }
    token = get_token()
    authorization_header(token) unless token.nil?
    request_with_retry(method, uri, body, extra_headers)
  end
end
```
take a look on this line:
```ruby
body = body.delete_if { |_, v| v.nil? }
```

Since body is a Array and not a ruby Hash, all elemts will be filtered from here, original array will be mutated and empty body to be send to the API. This is definitely a bug that need to be fixed. 

There is a similar issue listed here, but it's a bit different: https://github.com/auth0/ruby-auth0/issues/309

I think the line should be changed to be something like:
```ruby
body = body.dup.delete_if { |_, v| v.nil? } if body.kind_of?(Hash)
```

### Reproduction

Request:

```ruby
auth0_payload = {"type"=>"totp", "totp_secret"=>"MY_SECRET_ENCODED_IN_BASE32"}
auth0_client.update_all_user_authentication_methods(user.idp_sub, auth0_payload)
```
Error
`Auth0::BadRequest ({"statusCode":400,"error":"Bad Request","message":"Payload validation error: 'Expected type array but found type object'.","errorCode":"invalid_body"})`

OR if you do the following:

```ruby
auth0_payload = [{"type"=>"totp", "totp_secret"=>"MY_SECRET_ENCODED_IN_BASE32"}]
auth0_client.update_all_user_authentication_methods(user.idp_sub, auth0_payload)
```

it will make `auth0_payload` to became empty array, and empty body will be send to the API

### Additional context

_No response_

### ruby-auth0 version

5.12.0

### Ruby version

2.7.0

### PR DESCRIPTION
**Pull request by carlastabile**
### Changes

This PR attempts to fix #476 

### References

Please note any links that are not publicly accessible.

### Testing

Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.

* [x] This change adds unit test coverage
* [x] This change adds integration test coverage
* [ ] This change has been tested on the latest version of Ruby

### Checklist

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] All existing and new tests complete without errors
* [ ] Rubocop passes on all added/modified files
* [ ] All active GitHub checks have passed

### CODE REVIEW

File: spec/lib/auth0/mixins/httpproxy_spec.rb [hunk 1]
```diff
@@ -279,6 +279,19 @@ def expected_payload(method, overrides = {})
         expect { @instance.send(http_method, '/test') }.not_to raise_error
       end
 
+      it "should handle array parameters for #{http_method} method" do
```
Comment (arpit-jn) [inline spec/lib/auth0/mixins/httpproxy_spec.rb]: We should also add unit tests covering this fix. 

```
context 'when body is an Array' do
  let(:payload) { [{ permission_name: 'read:data', resource_server_identifier: 'https://api.example.com' }] }

  it 'sends the array as-is without wrapping in a Hash' do
    expect(RestClient::Request).to receive(:execute) do |args|
      parsed = JSON.parse(args[:payload], symbolize_names: true)
      expect(parsed).to be_an(Array)
      expect(parsed).to eq(payload)
    end.and_return(StubResponse.new('[]', true, 200))

    subject.post('/test', payload)
  end
end
```

Also let's add a regression test confirming Hash payloads are unaffected. CI should catch it but let's be explicit.
